/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SherbimetRouteImport } from './routes/sherbimet'
import { Route as RrethNeshRouteImport } from './routes/rreth-nesh'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LajmeIndexRouteImport } from './routes/lajme.index'
import { Route as LajmeSlugRouteImport } from './routes/lajme.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SherbimetRoute = SherbimetRouteImport.update({
  id: '/sherbimet',
  path: '/sherbimet',
  getParentRoute: () => rootRouteImport,
} as any)
const RrethNeshRoute = RrethNeshRouteImport.update({
  id: '/rreth-nesh',
  path: '/rreth-nesh',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LajmeIndexRoute = LajmeIndexRouteImport.update({
  id: '/lajme/',
  path: '/lajme/',
  getParentRoute: () => rootRouteImport,
} as any)
const LajmeSlugRoute = LajmeSlugRouteImport.update({
  id: '/lajme/$slug',
  path: '/lajme/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/sherbimet': typeof SherbimetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lajme/$slug': typeof LajmeSlugRoute
  '/lajme/': typeof LajmeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/sherbimet': typeof SherbimetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lajme/$slug': typeof LajmeSlugRoute
  '/lajme': typeof LajmeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/sherbimet': typeof SherbimetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/lajme/$slug': typeof LajmeSlugRoute
  '/lajme/': typeof LajmeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kontakt'
    | '/rreth-nesh'
    | '/sherbimet'
    | '/sitemap.xml'
    | '/admin'
    | '/lajme/$slug'
    | '/lajme/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kontakt'
    | '/rreth-nesh'
    | '/sherbimet'
    | '/sitemap.xml'
    | '/admin'
    | '/lajme/$slug'
    | '/lajme'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kontakt'
    | '/rreth-nesh'
    | '/sherbimet'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/lajme/$slug'
    | '/lajme/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KontaktRoute: typeof KontaktRoute
  RrethNeshRoute: typeof RrethNeshRoute
  SherbimetRoute: typeof SherbimetRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LajmeSlugRoute: typeof LajmeSlugRoute
  LajmeIndexRoute: typeof LajmeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sherbimet': {
      id: '/sherbimet'
      path: '/sherbimet'
      fullPath: '/sherbimet'
      preLoaderRoute: typeof SherbimetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rreth-nesh': {
      id: '/rreth-nesh'
      path: '/rreth-nesh'
      fullPath: '/rreth-nesh'
      preLoaderRoute: typeof RrethNeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lajme/': {
      id: '/lajme/'
      path: '/lajme'
      fullPath: '/lajme/'
      preLoaderRoute: typeof LajmeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lajme/$slug': {
      id: '/lajme/$slug'
      path: '/lajme/$slug'
      fullPath: '/lajme/$slug'
      preLoaderRoute: typeof LajmeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KontaktRoute: KontaktRoute,
  RrethNeshRoute: RrethNeshRoute,
  SherbimetRoute: SherbimetRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LajmeSlugRoute: LajmeSlugRoute,
  LajmeIndexRoute: LajmeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
